In [1]:
# Import the dependencies
import pandas as pd
import numpy as np
import datetime

# Plotting
import matplotlib.pyplot as plt
import seaborn as sns

# ORM Stuff
from sqlalchemy import create_engine, inspect, text, func
from sqlalchemy.orm import Session
from sqlalchemy.ext.automap import automap_base

In [2]:
USERNAME = "postgres"
PASSWORD = "postgres"
HOST = "localhost"
PORT = 5432
DATABASE = "Project_2_DB"
connection_str = f"postgresql://{USERNAME}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"

# Create Engine
engine = create_engine(connection_str)

In [3]:
# Create the inspector and connect it to the engine
inspector = inspect(engine)

# Collect the names of tables within the database
tables = inspector.get_table_names()

# Using the inspector to print the column names within the 'dow' table and its types
for table in tables:
    print(table)
    print("--------")
    columns = inspector.get_columns(table)
    for column in columns:
        print(column["name"], column["type"])

    print()

contacts
--------
contact_id INTEGER
first_name VARCHAR(20)
last_name VARCHAR(20)
email VARCHAR(60)

campaign
--------
cf_id INTEGER
contact_id INTEGER
company_name VARCHAR(50)
description VARCHAR(55)
goal INTEGER
pledged INTEGER
outcome VARCHAR(10)
backers_count INTEGER
country VARCHAR(2)
currency VARCHAR(3)
launch_date DATE
end_date DATE
category_id VARCHAR(5)
subcategory_id VARCHAR(8)

categories
--------
category_id VARCHAR(5)
category VARCHAR(25)

subcategories
--------
subcategory_id VARCHAR(8)
subcategory VARCHAR(25)

In [4]:
category_df = pd.read_csv('Resources/category.csv')
category_df.head()

  category_id      category
0        cat1          food
1        cat2         music
2        cat3    technology
3        cat4       theater
4        cat5  film & video

In [5]:
category_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   category_id  9 non-null      object
 1   category     9 non-null      object
dtypes: object(2)
memory usage: 272.0+ bytes

In [6]:
# Write to SQL (NOTE I AM USING con=engine) THIS IS WHAT WORKS APPARENTLY WHEN WRITING OUT DATA
category_df.to_sql(name="categories", con=engine, index=False, if_exists="append", method="multi")

9

In [7]:
sub_category_df = pd.read_csv('Resources/subcategory.csv')
sub_category_df.head()

  subcategory_id  subcategory
0        subcat1  food trucks
1        subcat2         rock
2        subcat3          web
3        subcat4        plays
4        subcat5  documentary

In [8]:
sub_category_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subcategory_id  24 non-null     object
 1   subcategory     24 non-null     object
dtypes: object(2)
memory usage: 512.0+ bytes

In [9]:
# Write to SQL (NOTE I AM USING con=engine) THIS IS WHAT WORKS APPARENTLY WHEN WRITING OUT DATA
sub_category_df.to_sql(name="subcategories", con=engine, index=False, if_exists="append", method="multi")

24

In [10]:
contacts_df = pd.read_csv('Resources/contacts.csv')
contacts_df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Resources/contacts.csv'

In [ ]:
contacts_df.info()

In [ ]:
# Write to SQL (NOTE I AM USING con=engine) THIS IS WHAT WORKS APPARENTLY WHEN WRITING OUT DATA
contacts_df.to_sql(name="contacts", con=engine, index=False, if_exists="append", method="multi")

In [ ]:
campaign_df = pd.read_csv('Resources/campaign.csv')
campaign_df.head()

In [ ]:
campaign_df.info()

In [ ]:
# Write to SQL (NOTE I AM USING con=engine) THIS IS WHAT WORKS APPARENTLY WHEN WRITING OUT DATA
campaign_df.to_sql(name="campaign", con=engine, index=False, if_exists="append", method="multi")